name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: environment setup
      run: export VERSION=$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devwvscode:${VERSION}      
    - name: Docker tag as latest
      run: docker tag devwvscode:${VERSION} devwvscode:latest
