name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        VERSION=$(date +%s)
        docker build . --file Dockerfile --tag devwvscode:${VERSION}
        docker tag devwvscode:${VERSION} devwvscode:latest
      shell: bash
