name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      VERSION: (date +%s)
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image devwvscode:${VERSION}
      run: docker build . --file Dockerfile --tag devwvscode:${VERSION}
      shell: bash
    - name: run image ${VERSION}
      run: docker run devwvscode:${VERSION}
