name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image devwvscode:latest
      run: docker build . --file Dockerfile --tag devwvscode:latest
      shell: bash
    - name: run image devwvscode:latest
      run: docker run devwvscode:latest cat /app/inventory.txt
      shell: bash
