name: Docker Image CI

env:
  version: $(date +%s)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devwvscode:$version
    - name: Docker tag as latest
      run: docker tag devwvscode:$version devwvscode:latest
