name: Publish Docker
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ebmarquez/vscode-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        tags: latest
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ebmarquez/vscode-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
