name: Publish Docker
on:
  push:
    branches:
      - main
  schedule:
  # first day of the month at 2:00 AM.
    - cron: '0 2 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup version variable
      shell: bash
      run: export VERSION=`test`
    - name: test version
      shell: bash
      run: |
        echo "VERSION: $VERSION"
        echo "VERSION: $env.VERSION"
      #  echo ${{ GITHUB_ENV }}
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ebmarquez/vscode-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        tags: latest