name: Publish Docker
on:
  push:
    branches:
      - main
  schedule:
  # first day of the month at 2:00 AM.
    - cron: '0 2 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: VERSION=`date +"%y%m.%d.%H%M"` >> $GITHUB_ENV
    - run: echo "1  ${{ env.VERSION }}"
    - run: echo "2  ${{ VERSION }}"
    - uses: actions/checkout@master
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ebmarquez/vscode-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        tags: latest, ${{ env.VERSION }}