name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test env
    - run: echo $GITHUB_RUN_NUMBER
    - run: echo $secrets.DOCKER_USERNAME
    - uses: actions/checkout@master
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ebmarquez/vscode-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ENV.GITHUB_RUN_NUMBER}}"
