name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: ebmarquez/vscode-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.GITHUB_RUN_NUMBER}}"
