- name: Update GitHub Profile README
  uses: theboi/github-update-readme@v1.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    header: "Header Tets"
    subhead: "sub header"
    footer: "footer"
